// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxVMUeTYZVoiyFLqV9uP2mEmNyRyN3NE',
    appId: '1:470827117758:web:650e93d411dd6eaea682ef',
    messagingSenderId: '470827117758',
    projectId: 'abshr-d27bc',
    authDomain: 'abshr-d27bc.firebaseapp.com',
    storageBucket: 'abshr-d27bc.firebasestorage.app',
    measurementId: 'G-CXQM6BBNFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_AL0dVfbprQsw-CgePKOWcdte2w0KDM',
    appId: '1:470827117758:android:2183b0cdb0a880daa682ef',
    messagingSenderId: '470827117758',
    projectId: 'abshr-d27bc',
    storageBucket: 'abshr-d27bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDeqsw8ItM82NKLBsJv9pXiTgOQ3JOWSo',
    appId: '1:470827117758:ios:182d94c564ebc323a682ef',
    messagingSenderId: '470827117758',
    projectId: 'abshr-d27bc',
    storageBucket: 'abshr-d27bc.firebasestorage.app',
    iosBundleId: 'com.example.abshr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDeqsw8ItM82NKLBsJv9pXiTgOQ3JOWSo',
    appId: '1:470827117758:ios:182d94c564ebc323a682ef',
    messagingSenderId: '470827117758',
    projectId: 'abshr-d27bc',
    storageBucket: 'abshr-d27bc.firebasestorage.app',
    iosBundleId: 'com.example.abshr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxVMUeTYZVoiyFLqV9uP2mEmNyRyN3NE',
    appId: '1:470827117758:web:bb1b62c3c593017aa682ef',
    messagingSenderId: '470827117758',
    projectId: 'abshr-d27bc',
    authDomain: 'abshr-d27bc.firebaseapp.com',
    storageBucket: 'abshr-d27bc.firebasestorage.app',
    measurementId: 'G-H0YTR9PZ96',
  );
}
